export ZSH=$HOME/.oh-my-zsh

ZSH_THEME="fishy"

DISABLE_AUTO_UPDATE=true
DISABLE_UPDATE_PROMPT=true

plugins=(git)

source $ZSH/oh-my-zsh.sh

alias ls='exa -g'
alias la='ls -laah'
alias tree='tree -C'

export EDITOR=vim
export VISUAL=$EDITOR

export NVM_DIR=/opt/nvm
export NVM_SYMLINK_CURRENT=true

[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && . "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

export PATH=${NVM_DIR}/current/bin:${PATH}

source /usr/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
