source /etc/vim/vimrc

if has("autocmd")
  au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g`\"" | endif
endif

set pastetoggle=<F2>
syntax on
set ignorecase
set smartcase
set hlsearch
set incsearch
set wrapscan
set mouse-=a
set fileformat=unix
set encoding=utf-8
set history=500
set timeoutlen=150
set laststatus=2
set scrolloff=5
set hidden
set autoread
set ruler
set backspace=eol,start,indent
set whichwrap+=<,>,h,l,[,]
set splitbelow
set splitright
set lazyredraw
set magic
set showmatch
set matchtime=5
set nojoinspaces
set showcmd
set list listchars=tab:»·,trail:·,nbsp:·
set wildmenu
set wildmode=list:longest,full
set wildignore=*.o,*~,*.pyc,*.so,*.zip
set tabstop=2
set shiftwidth=2
set expandtab
set smarttab
set autoindent
