export ZSH=$HOME/.oh-my-zsh

# ZSH_THEME="codespaces"
ZSH_THEME="fishy"

DISABLE_AUTO_UPDATE=true
DISABLE_UPDATE_PROMPT=true

plugins=(git)

source $ZSH/oh-my-zsh.sh

alias ls='exa -g'
alias la='ls -laah'
alias tree='tree -C'

export EDITOR=vim
export VISUAL=$EDITOR

export PIPX_HOME="/usr/local/py-utils"
export PIPX_BIN_DIR="${PIPX_HOME}/bin"
export PATH=${HOME}/.local/bin:${PIPX_BIN_DIR}:$PATH

source /usr/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
